service: sls
frameworkVersion: '3'

provider:
  name: aws
  stage: dev
  runtime: python3.11
  memorySize: 512
  region: us-east-1
  iam:
    role:
      statements:
        # Allow functions to list all buckets
        - Effect: Allow
          Action: 's3:ListBucket'
          Resource: '*'
        # Allow functions to read/write objects in a bucket
        - Effect: Allow
          Action:
            - 's3:GetObject'
            - 's3:PutObject'
          Resource:
            - '*'
  s3:
    slsBucket:
      name: sls-etl

package:
  individually: true
  patterns:
      - '!**'

functions:
  thumbnail-generator:
    handler: handler.main
    package:
      patterns:
        - './handler.py'
    layers:
      - arn:aws:lambda:us-east-1:770693421928:layer:Klayers-p311-Pillow:2
    events:
      - s3:
          bucket: slsBucket
          event: s3:ObjectCreated:*
          rules:
            - prefix: input/
